/**
 * Single source of truth for marketplace category colors.
 * Homepage cards, heroes, filters, and bottom CTAs all resolve from here.
 */

export const CATEGORY_THEMES = {
  'buy-sell': {
    id: 'buy-sell',
    name: 'Buy & Sell',
    description: 'Post anything you want to sell or find items to purchase',
    route: '/buy-sell',
    heroTheme: 'emerald',
    filterTheme: 'green',
    ctaTheme: 'green',
    color: 'from-green-500 to-emerald-500',
    bgColor: 'bg-gradient-to-br from-green-100 to-emerald-100',
    iconColor: 'text-green-600',
    borderColor: 'border-green-200',
    hoverBg: 'hover:from-green-500 hover:to-emerald-500',
    accentText: 'text-green-600',
    accentButton: 'bg-green-600 hover:bg-green-700',
    spinnerBorder: 'border-green-600',
  },
  business: {
    id: 'business',
    name: 'Business & Companies',
    description: 'Find business opportunities, company listings, and commercial services',
    route: '/business',
    heroTheme: 'violet',
    filterTheme: 'purple',
    ctaTheme: 'purple',
    color: 'from-gray-500 to-blue-500',
    bgColor: 'bg-gradient-to-br from-gray-100 to-blue-100',
    iconColor: 'text-gray-600',
    borderColor: 'border-gray-200',
    hoverBg: 'hover:from-gray-500 hover:to-blue-500',
    accentText: 'text-violet-600',
    accentButton: 'bg-violet-600 hover:bg-violet-700',
    spinnerBorder: 'border-violet-600',
  },
  services: {
    id: 'services',
    name: 'Services and Solutions',
    description: 'Professional services, consulting, and business solutions',
    route: '/services',
    heroTheme: 'amber',
    filterTheme: 'amber',
    ctaTheme: 'amber',
    color: 'from-amber-500 to-orange-500',
    bgColor: 'bg-gradient-to-br from-amber-100 to-orange-100',
    iconColor: 'text-amber-600',
    borderColor: 'border-amber-200',
    hoverBg: 'hover:from-amber-500 hover:to-orange-500',
    accentText: 'text-amber-600',
    accentButton: 'bg-amber-600 hover:bg-amber-700',
    spinnerBorder: 'border-amber-600',
  },
  property: {
    id: 'property',
    name: 'Property and Solutions',
    description: 'Browse properties for sale, rent, and real estate investments',
    route: '/property',
    heroTheme: 'propertyViolet',
    filterTheme: 'purple',
    ctaTheme: 'purple',
    color: 'from-violet-500 to-purple-500',
    bgColor: 'bg-gradient-to-br from-violet-100 to-purple-100',
    iconColor: 'text-violet-600',
    borderColor: 'border-violet-200',
    hoverBg: 'hover:from-violet-500 hover:to-purple-500',
    accentText: 'text-violet-600',
    accentButton: 'bg-violet-600 hover:bg-violet-700',
    spinnerBorder: 'border-violet-600',
  },
  jobs: {
    id: 'jobs',
    name: 'Jobs & Vacancies',
    description: 'Find remote and local jobs, or post openings for candidates',
    route: '/jobs',
    heroTheme: 'blue',
    filterTheme: 'blue',
    ctaTheme: 'blue',
    color: 'from-sky-500 to-blue-600',
    bgColor: 'bg-gradient-to-br from-sky-100 to-blue-100',
    iconColor: 'text-sky-600',
    borderColor: 'border-sky-200',
    hoverBg: 'hover:from-sky-500 hover:to-blue-600',
    accentText: 'text-blue-600',
    accentButton: 'bg-blue-600 hover:bg-blue-700',
    spinnerBorder: 'border-blue-600',
  },
  software: {
    id: 'software',
    name: 'Software & Code',
    description: 'Sell scripts, themes, plugins and apps',
    route: '/software',
    heroTheme: 'blue',
    filterTheme: 'blue',
    ctaTheme: 'blue',
    color: 'from-blue-500 to-indigo-600',
    bgColor: 'bg-gradient-to-br from-blue-100 to-indigo-100',
    iconColor: 'text-blue-600',
    borderColor: 'border-blue-200',
    hoverBg: 'hover:from-blue-500 hover:to-indigo-600',
    accentText: 'text-blue-600',
    accentButton: 'bg-blue-600 hover:bg-blue-700',
    spinnerBorder: 'border-blue-600',
  },
  events: {
    id: 'events',
    name: 'Events & Venues',
    description: 'Explore events and venues — conferences, concerts, halls and more',
    route: '/events-venues',
    heroTheme: 'purple',
    filterTheme: 'purple',
    ctaTheme: 'purple',
    color: 'from-purple-500 to-pink-500',
    bgColor: 'bg-gradient-to-br from-purple-100 to-pink-100',
    iconColor: 'text-purple-600',
    borderColor: 'border-purple-200',
    hoverBg: 'hover:from-purple-500 hover:to-pink-500',
    accentText: 'text-purple-600',
    accentButton: 'bg-purple-600 hover:bg-purple-700',
    spinnerBorder: 'border-purple-600',
  },
  sponsored: {
    id: 'sponsored',
    name: 'Sponsored Ads',
    description: 'Premium sponsored advertising placements',
    route: '/sponsored-adverts',
    heroTheme: 'violet',
    filterTheme: 'purple',
    ctaTheme: 'purple',
    color: 'from-purple-500 to-indigo-500',
    bgColor: 'bg-gradient-to-br from-purple-100 to-indigo-100',
    iconColor: 'text-purple-600',
    borderColor: 'border-purple-200',
    hoverBg: 'hover:from-purple-500 hover:to-indigo-500',
    accentText: 'text-purple-600',
    accentButton: 'bg-purple-600 hover:bg-purple-700',
    spinnerBorder: 'border-purple-600',
  },
  promoted: {
    id: 'promoted',
    name: 'Promoted Ads',
    description: 'Promoted content and advertising campaigns',
    route: '/promoted-adverts',
    heroTheme: 'orange',
    filterTheme: 'amber',
    ctaTheme: 'orange',
    color: 'from-red-500 to-pink-500',
    bgColor: 'bg-gradient-to-br from-red-100 to-pink-100',
    iconColor: 'text-red-600',
    borderColor: 'border-red-200',
    hoverBg: 'hover:from-red-500 hover:to-pink-500',
    accentText: 'text-red-600',
    accentButton: 'bg-red-600 hover:bg-red-700',
    spinnerBorder: 'border-red-600',
  },
  banner: {
    id: 'banner',
    name: 'Banner Ads',
    description: 'Display banner advertising solutions',
    route: '/banner-adverts',
    heroTheme: 'indigo',
    filterTheme: 'purple',
    ctaTheme: 'purple',
    color: 'from-indigo-500 to-blue-500',
    bgColor: 'bg-gradient-to-br from-indigo-100 to-blue-100',
    iconColor: 'text-indigo-600',
    borderColor: 'border-indigo-200',
    hoverBg: 'hover:from-indigo-500 hover:to-blue-500',
    accentText: 'text-indigo-600',
    accentButton: 'bg-indigo-600 hover:bg-indigo-700',
    spinnerBorder: 'border-indigo-600',
  },
  featured: {
    id: 'featured',
    name: 'Featured Ads',
    description: 'Premium featured listings and highlighted content',
    route: '/featured',
    heroTheme: 'gold',
    filterTheme: 'amber',
    ctaTheme: 'amber',
    color: 'from-yellow-500 to-orange-500',
    bgColor: 'bg-gradient-to-br from-yellow-100 to-orange-100',
    iconColor: 'text-yellow-600',
    borderColor: 'border-yellow-200',
    hoverBg: 'hover:from-yellow-500 hover:to-orange-500',
    accentText: 'text-amber-600',
    accentButton: 'bg-amber-600 hover:bg-amber-700',
    spinnerBorder: 'border-amber-600',
  },
  funding: {
    id: 'funding',
    name: 'Funding & Crowdfunding',
    description: 'Raise business funding via loan or share partnership campaigns',
    route: '/funding',
    heroTheme: 'emerald',
    filterTheme: 'green',
    ctaTheme: 'emerald',
    color: 'from-[#02a95c] to-emerald-600',
    bgColor: 'bg-gradient-to-br from-green-100 to-emerald-100',
    iconColor: 'text-[#02a95c]',
    borderColor: 'border-emerald-200',
    hoverBg: 'hover:from-[#02a95c] hover:to-emerald-600',
    accentText: 'text-emerald-600',
    accentButton: 'bg-emerald-600 hover:bg-emerald-700',
    spinnerBorder: 'border-emerald-600',
  },
  stores: {
    id: 'stores',
    name: 'Online Stores',
    description: 'Online stores and e-commerce marketplaces',
    route: '/stores',
    heroTheme: 'cyan',
    filterTheme: 'blue',
    ctaTheme: 'blue',
    color: 'from-cyan-500 to-blue-500',
    bgColor: 'bg-gradient-to-br from-cyan-100 to-blue-100',
    iconColor: 'text-cyan-600',
    borderColor: 'border-cyan-200',
    hoverBg: 'hover:from-cyan-500 hover:to-blue-500',
    accentText: 'text-cyan-600',
    accentButton: 'bg-cyan-600 hover:bg-cyan-700',
    spinnerBorder: 'border-cyan-600',
  },
  books: {
    id: 'books',
    name: 'Books & Literature',
    description: 'Educational books, novels, audiobooks, and digital publications',
    route: '/books',
    heroTheme: 'amber',
    filterTheme: 'amber',
    ctaTheme: 'amber',
    color: 'from-indigo-500 to-purple-500',
    bgColor: 'bg-gradient-to-br from-indigo-100 to-purple-100',
    iconColor: 'text-indigo-600',
    borderColor: 'border-indigo-200',
    hoverBg: 'hover:from-indigo-500 hover:to-purple-500',
    accentText: 'text-amber-700',
    accentButton: 'bg-amber-700 hover:bg-amber-800',
    spinnerBorder: 'border-amber-600',
  },
  vehicles: {
    id: 'vehicles',
    name: 'Vehicles & Transport',
    description: 'Cars, motorcycles, trucks, and transportation solutions',
    route: '/vehicles',
    heroTheme: 'red',
    filterTheme: 'red',
    ctaTheme: 'red',
    color: 'from-gray-500 to-red-500',
    bgColor: 'bg-gradient-to-br from-gray-100 to-red-100',
    iconColor: 'text-gray-600',
    borderColor: 'border-gray-200',
    hoverBg: 'hover:from-gray-500 hover:to-red-500',
    accentText: 'text-red-600',
    accentButton: 'bg-red-600 hover:bg-red-700',
    spinnerBorder: 'border-red-600',
  },
  donations: {
    id: 'donations',
    name: 'Charities and Donations',
    description: 'Humanitarian causes and charitable contributions',
    route: '/donations',
    heroTheme: 'rose',
    filterTheme: 'purple',
    ctaTheme: 'purple',
    color: 'from-pink-500 to-rose-500',
    bgColor: 'bg-gradient-to-br from-pink-100 to-rose-100',
    iconColor: 'text-pink-600',
    borderColor: 'border-pink-200',
    hoverBg: 'hover:from-pink-500 hover:to-rose-500',
    accentText: 'text-pink-600',
    accentButton: 'bg-pink-600 hover:bg-pink-700',
    spinnerBorder: 'border-pink-600',
  },
  images: {
    id: 'images',
    name: 'Stock Images & Media',
    description: 'Buy and sell admin-verified images for commercial and personal use',
    route: '/images',
    heroTheme: 'rose',
    filterTheme: 'purple',
    ctaTheme: 'purple',
    color: 'from-rose-500 to-pink-500',
    bgColor: 'bg-gradient-to-br from-rose-100 to-pink-100',
    iconColor: 'text-rose-600',
    borderColor: 'border-rose-200',
    hoverBg: 'hover:from-rose-500 hover:to-pink-500',
    accentText: 'text-rose-600',
    accentButton: 'bg-rose-600 hover:bg-rose-700',
    spinnerBorder: 'border-rose-600',
  },
  classifieds: {
    id: 'classifieds',
    name: 'Classifieds',
    description: 'General classified advertisements and listings',
    route: '/classifieds-ads',
    heroTheme: 'teal',
    filterTheme: 'green',
    ctaTheme: 'emerald',
    color: 'from-teal-500 to-green-500',
    bgColor: 'bg-gradient-to-br from-teal-100 to-green-100',
    iconColor: 'text-teal-600',
    borderColor: 'border-teal-200',
    hoverBg: 'hover:from-teal-500 hover:to-green-500',
    accentText: 'text-teal-600',
    accentButton: 'bg-teal-600 hover:bg-teal-700',
    spinnerBorder: 'border-teal-600',
  },
  affiliate: {
    id: 'affiliate',
    name: 'Affiliate Hub',
    description: 'Affiliate marketing programs and partnership opportunities',
    route: '/affiliates',
    heroTheme: 'rose',
    filterTheme: 'purple',
    ctaTheme: 'purple',
    color: 'from-pink-500 to-rose-500',
    bgColor: 'bg-gradient-to-br from-pink-100 to-rose-100',
    iconColor: 'text-pink-600',
    borderColor: 'border-pink-200',
    hoverBg: 'hover:from-pink-500 hover:to-rose-500',
    accentText: 'text-pink-600',
    accentButton: 'bg-pink-600 hover:bg-pink-700',
    spinnerBorder: 'border-pink-600',
  },
  resorts: {
    id: 'resorts',
    name: 'Resorts & Travel',
    description: 'Luxury resorts, vacation packages, and travel destinations',
    route: '/resorts-travel',
    heroTheme: 'cyan',
    filterTheme: 'blue',
    ctaTheme: 'blue',
    color: 'from-cyan-500 to-blue-500',
    bgColor: 'bg-gradient-to-br from-cyan-100 to-blue-100',
    iconColor: 'text-cyan-600',
    borderColor: 'border-cyan-200',
    hoverBg: 'hover:from-cyan-500 hover:to-blue-500',
    accentText: 'text-cyan-600',
    accentButton: 'bg-cyan-600 hover:bg-cyan-700',
    spinnerBorder: 'border-cyan-600',
  },
  investment: {
    id: 'investment',
    name: 'Businesses for Sale',
    description: 'Buy or sell online and physical businesses worldwide',
    route: '/businesses-for-sale',
    heroTheme: 'orange',
    filterTheme: 'amber',
    ctaTheme: 'orange',
    color: 'from-amber-500 to-orange-500',
    bgColor: 'bg-gradient-to-br from-amber-100 to-orange-100',
    iconColor: 'text-amber-600',
    borderColor: 'border-amber-200',
    hoverBg: 'hover:from-amber-500 hover:to-orange-500',
    accentText: 'text-orange-600',
    accentButton: 'bg-orange-600 hover:bg-orange-700',
    spinnerBorder: 'border-orange-600',
  },
};

/** Aliases so pages can look up by route slug or alternate ids */
const ALIASES = {
  affiliates: 'affiliate',
  'banner-adverts': 'banner',
  'sponsored-adverts': 'sponsored',
  'promoted-adverts': 'promoted',
  'featured-adverts': 'featured',
  'events-venues': 'events',
  'resorts-travel': 'resorts',
  'businesses-for-sale': 'investment',
  charities: 'donations',
  'buy_sell': 'buy-sell',
};

export function getCategoryTheme(categoryId) {
  if (!categoryId) return CATEGORY_THEMES['buy-sell'];
  const key = ALIASES[categoryId] || categoryId;
  return CATEGORY_THEMES[key] || CATEGORY_THEMES['buy-sell'];
}

export default CATEGORY_THEMES;
