import { getStorageAssetUrl } from './jobsHelpers';

export const parseJsonArray = (value, fallback) => {
  if (Array.isArray(value) && value.length) return value;
  if (typeof value === 'string') {
    try {
      const parsed = JSON.parse(value);
      if (Array.isArray(parsed) && parsed.length) return parsed;
    } catch {
      /* ignore */
    }
  }
  return fallback;
};

export const resolveStorageUrl = (path) => {
  if (!path || path === 'null') return null;
  return getStorageAssetUrl(path) || path;
};

export const mapSponsoredAdvertToForm = (ad) => ({
  advert_type: ad.advert_type || '',
  title: ad.title || '',
  tagline: ad.tagline || '',
  description: ad.description || '',
  category_id: ad.category_id?.toString() || ad.category?.id?.toString() || '',
  business_sale_type: ad.business_sale_type || '',
  business_sale_category: ad.business_sale_category || '',
  condition: ad.condition || '',
  price: ad.price?.toString() || '',
  currency: ad.currency || 'GBP',
  country: ad.country || '',
  city: ad.city || '',
  latitude: ad.latitude?.toString() || '',
  longitude: ad.longitude?.toString() || '',
  location_precision: ad.location_precision || 'approximate',
  main_image: null,
  additional_images: [],
  video_link: ad.video_link || ad.video_url || '',
  seller_name: ad.seller_name || ad.contact_name || '',
  business_name: ad.business_name || '',
  phone: ad.phone || ad.contact_phone || '',
  email: ad.email || ad.contact_email || '',
  website: ad.website || '',
  social_links: Array.isArray(ad.social_links) ? ad.social_links : [],
  logo: null,
  verified_seller: Boolean(ad.verified_seller || ad.is_verified_seller),
  sponsorship_tier: ad.sponsorship_tier || 'basic',
  sponsorship_price: ad.sponsorship_price || 0,
});

export const mapDonationToForm = (d) => ({
  title: d.title || '',
  description: d.description || '',
  story: d.story || '',
  category: d.category || d.cause_type || 'disaster',
  organizer_name: d.organizer_name || '',
  organizer_email: d.organizer_email || '',
  organizer_phone: d.organizer_phone || '',
  goal_amount: d.goal_amount?.toString() || d.target_amount?.toString() || '',
  currency: d.currency || 'USD',
  deadline: d.deadline?.slice?.(0, 10) || d.deadline || '',
  country: d.country || '',
  city: d.city || '',
  cover_image: null,
  images: [],
  video_url: d.video_url || '',
  beneficiaries: parseJsonArray(d.beneficiaries, [{ name: '', relationship: '', age: '' }]),
  use_of_funds: d.use_of_funds || '',
  milestones: parseJsonArray(d.milestones, [{ milestone: '', expected_date: '' }]),
});

export const mapVehicleToForm = (v) => ({
  advert_type: v.advert_type || '',
  title: v.title || '',
  tagline: v.tagline || '',
  category_id: v.category_id?.toString() || v.category?.id?.toString() || '',
  make_id: v.make_id?.toString() || v.make?.id?.toString() || '',
  model_id: v.model_id?.toString() || v.model?.id?.toString() || '',
  custom_model: v.custom_model || '',
  year: v.year?.toString() || '',
  mileage: v.mileage?.toString() || '',
  fuel_type: v.fuel_type ? v.fuel_type.charAt(0).toUpperCase() + v.fuel_type.slice(1) : '',
  transmission: v.transmission
    ? v.transmission.charAt(0).toUpperCase() + v.transmission.slice(1)
    : '',
  condition: v.condition
    ? v.condition.split('_').map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')
    : '',
  price: v.price?.toString() || '',
  price_type: v.price_type || 'fixed',
  is_negotiable: Boolean(v.is_negotiable || v.negotiable),
  main_image: null,
  videoUrl: v.video_link || v.video_url || '',
  engine_size: v.engine_size?.toString() || '',
  doors: v.doors?.toString() || '',
  seats: v.seats?.toString() || '',
  color: v.color || '',
  body_type: v.body_type
    ? v.body_type.charAt(0).toUpperCase() + v.body_type.slice(1)
    : '',
  vin: v.vin || '',
  registration_number: v.registration_number || '',
  description: v.description || '',
  contact_name: v.contact_name || '',
  business_name: v.business_name || '',
  contact_phone: v.contact_phone || v.phone || '',
  contact_email: v.contact_email || v.email || '',
  website: v.website || '',
  address: v.address || '',
  city: v.city || '',
  country: v.country || '',
  show_exact_location: v.show_exact_location ?? true,
  pricing_plan_id: v.pricing_plan_id || 1,
});

export const mapPropertyToForm = (p) => ({
  property_type: p.property_type || '',
  category: p.category || 'buy',
  title: p.title || '',
  tagline: p.tagline || '',
  country: p.country || '',
  city: p.city || '',
  region: p.region || '',
  address: p.address || '',
  cover_image: null,
  additional_images: [],
  video_tour_link: p.video_tour_link || p.video_url || '',
  bedrooms: p.bedrooms?.toString() || '',
  bathrooms: p.bathrooms?.toString() || '',
  property_size: p.property_size?.toString() || '',
  size_unit: p.size_unit || 'sq_ft',
  furnished: Boolean(p.furnished),
  parking_spaces: p.parking_spaces?.toString() || '',
  commercial_type: p.commercial_type || '',
  floor_area: p.floor_area?.toString() || '',
  footfall_rating: p.footfall_rating || '',
  accessibility_features: Boolean(p.accessibility_features),
  zoning_type: p.zoning_type || '',
  warehouse_size: p.warehouse_size?.toString() || '',
  loading_bays: p.loading_bays?.toString() || '',
  power_capacity: p.power_capacity || '',
  ceiling_height: p.ceiling_height?.toString() || '',
  land_size: p.land_size?.toString() || '',
  land_type: p.land_type || '',
  planning_permission: p.planning_permission || '',
  soil_quality: p.soil_quality || '',
  premium_features: parseJsonArray(p.premium_features, []),
  security_features: parseJsonArray(p.security_features, []),
  view_type: p.view_type || '',
  rental_yield: p.rental_yield?.toString() || '',
  occupancy_rate: p.occupancy_rate?.toString() || '',
  current_rental_income: p.current_rental_income?.toString() || '',
  roi_percentage: p.roi_percentage?.toString() || '',
  price: p.price?.toString() || '',
  currency: p.currency || 'USD',
  negotiable: Boolean(p.negotiable),
  deposit: p.deposit?.toString() || '',
  service_charges: p.service_charges?.toString() || '',
  maintenance_fees: p.maintenance_fees?.toString() || '',
  seller_name: p.seller_name || p.contact_name || '',
  seller_company: p.seller_company || p.business_name || '',
  seller_phone: p.seller_phone || p.contact_phone || '',
  seller_email: p.seller_email || p.contact_email || '',
  seller_website: p.seller_website || p.website || '',
  seller_logo: null,
  verified_agent: Boolean(p.verified_agent),
  overview: p.overview || p.description || '',
  key_features: p.key_features || '',
  location_highlights: p.location_highlights || '',
  nearby_amenities: p.nearby_amenities || '',
  transport_links: p.transport_links || '',
  additional_notes: p.additional_notes || '',
  amenities: parseJsonArray(p.amenities, []),
  latitude: p.latitude?.toString() || '',
  longitude: p.longitude?.toString() || '',
  show_exact_location: p.show_exact_location ?? true,
  advert_type: p.advert_type || p.promotion_tier || 'standard',
  terms_accepted: true,
  accuracy_confirmed: true,
});

export const mapBannerToForm = (b) => ({
  bannerType: b.banner_type || b.type || 'image',
  businessName: b.business_name || '',
  contactPerson: b.contact_person || '',
  email: b.email || '',
  phone: b.phone || '',
  website: b.website_url || b.website || '',
  businessLogo: null,
  verifiedBadge: Boolean(b.is_verified_business || b.verified_badge),
  bannerTitle: b.title || '',
  tagline: b.tagline || '',
  category: b.banner_category_id?.toString() || b.category_id?.toString() || '',
  country: b.country || '',
  city: b.city || '',
  targetAudience: b.target_audience || '',
  bannerFile: null,
  destinationLink: b.destination_link || b.target_url || '',
  callToAction: b.call_to_action || '',
  bannerSize: b.banner_size || b.size || '728x90',
  description: b.description || '',
  keySellingPoints: b.key_selling_points || '',
  offerDetails: b.offer_details || '',
  validityStart: b.validity_start?.slice?.(0, 10) || b.start_date?.slice?.(0, 10) || '',
  validityEnd: b.validity_end?.slice?.(0, 10) || b.end_date?.slice?.(0, 10) || '',
  targetCountries: Array.isArray(b.target_countries) ? b.target_countries : [],
  targetCategories: Array.isArray(b.target_categories) ? b.target_categories : [],
  targetDevices: b.target_devices || 'both',
  selectedTier: b.promotion_tier || 'standard',
  termsAccepted: true,
  privacyAccepted: true,
});

export const mapBuySellAdvertToForm = (ad) => ({
  itemType: ad.item_type || ad.advert_type || 'for_sale',
  title: ad.title || '',
  condition: ad.condition || '',
  brand: ad.brand || '',
  model: ad.model || '',
  color: ad.color || '',
  dimensions: ad.dimensions || '',
  weight: ad.weight?.toString() || '',
  category_id: ad.category_id?.toString() || ad.category?.id?.toString() || '',
  main_image_url: ad.main_image || ad.main_image_url || (Array.isArray(ad.images) ? ad.images[0] : '') || '',
  additional_image_urls: Array.isArray(ad.images) ? ad.images.slice(1) : (ad.additional_images || []),
  description: ad.description || '',
  price: ad.price?.toString() || '',
  currency: ad.currency || 'USD',
  negotiable: Boolean(ad.negotiable),
  sellerName: ad.seller_name || ad.contact_name || '',
  seller_email: ad.seller_email || ad.contact_email || ad.email || '',
  preferred_contact: ad.preferred_contact || 'email',
  sellerPhone: ad.seller_phone || ad.contact_phone || ad.phone || '',
  sellerCompany: ad.seller_company || ad.business_name || '',
  sellerWebsite: ad.seller_website || ad.website || '',
  sellerLogo: null,
  verifiedSeller: Boolean(ad.verified_seller),
  location: ad.location || [ad.city, ad.country].filter(Boolean).join(', '),
  country: ad.country || '',
  city: ad.city || '',
  address: ad.address || '',
  postalCode: ad.postal_code || ad.postalCode || '',
  coordinates: ad.coordinates || null,
  privacyMode: Boolean(ad.privacy_mode),
  upsellType: ad.promotion_plan || ad.upsell_type || 'basic',
  termsAccepted: true,
  accuracyConfirmed: true,
});
